jobs:
  include:
    - stage: setup_kafka
      before_script:
      - wget https://www.apache.org/dyn/closer.cgi?path=/kafka/2.1.0/kafka_2.11-2.1.0.tgz
      - tar -xvf kafka_2.11-2.1.0.tgz
      - cd kafka_2.11-2.1.0
      script: bin/zookeeper-server-start.sh config/zookeeper.properties
    - stage: build_and_test
      install: ./gradlew assemble
      language: java
      jdk:
        - oraclejdk8
        - oraclejdk9
        - openjdk8
        - openjdk9
      before_script:
        - chmod a+x gradlew
      script: ./gradlew build
      notifications:
        slack: kalium-alkalio:TKKbLCQK8wW6HLPGfrGWyKUS