env:
  global:
    - CC_TEST_REPORTER_ID=6728d7a9a1ed449e33455dbff8d8b4b8024b7afe9aee4208144cd8c6fdefa1db
before_script:
  - wget https://www-eu.apache.org/dist/kafka/2.1.0/kafka_2.11-2.1.0.tgz
  - rm -rfv /tmp/kafka*
  - rm -rfv /tmp/zookeeper*
  - rm -rfv kafka_2.11-2.1.0
  - tar -xvf kafka_2.11-2.1.0.tgz
  - kafka_2.11-2.1.0/bin/zookeeper-server-start.sh kafka_2.11-2.1.0/config/zookeeper.properties&
  - sleep 20s
  - kafka_2.11-2.1.0/bin/kafka-server-start.sh kafka_2.11-2.1.0/config/server.properties&
  - sleep 20s
  - kafka_2.11-2.1.0/bin/kafka-topics.sh --create --zookeeper localhost:2181 --replication-factor 1 --partitions 1 --topic Payment&
  - kafka_2.11-2.1.0/bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic test --from-beginning&
  - chmod a+x gradlew
  - url -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
install: ./gradlew assemble
language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8
  - openjdk9
script: ./gradlew build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
notifications:
  slack: kalium-alkalio:TKKbLCQK8wW6HLPGfrGWyKUS
