jobs:
  include:
    - stage: setup_kafka
      before_script: chmod a+x ./scripts/install_and_run_kafka.sh
      script: ./scripts/install_and_run_kafka.sh
    - stage: build_and_test
      install: ./gradlew assemble
      language: java
      jdk:
        - oraclejdk8
        - oraclejdk9
        - openjdk8
        - openjdk9
      before_script:
        - chmod a+x gradlew
      script: ./gradlew build
      notifications:
        slack: kalium-alkalio:TKKbLCQK8wW6HLPGfrGWyKUS