before_script:
  - wget https://www-eu.apache.org/dist/kafka/2.1.0/kafka_2.11-2.1.0.tgz
  - tar -xvf kafka_2.11-2.1.0.tgz
  - kafka_2.11-2.1.0/bin/zookeeper-server-start.sh config/zookeeper.properties&
  - sleep 10s
  - kafka_2.11-2.1.0/bin/kafka-server-start.sh config/server.properties&
  - sleep 10s
  - chmod a+x gradlew
install: ./gradlew assemble
language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8
  - openjdk9
script: ./gradlew build  --illegal-access=warn --debug
notifications:
  slack: kalium-alkalio:TKKbLCQK8wW6HLPGfrGWyKUS