package io.alkal.kalium.kafka.tests;/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import io.alkal.kalium.Kalium;
import io.alkal.kalium.interfaces.KaliumQueueAdapter;
import io.alkal.kalium.kafka.KaliumKafkaQueueAdapter;
import org.junit.Assert;
import org.junit.Test;
import org.mockito.ArgumentCaptor;
import org.mockito.Mockito;

import java.util.UUID;


public class KaliumKafkaBasicTest {

    public static final String KAFKA_ENDPOINT = "localhost:9092";

    @Test
    public void testItShouldCallReactionMethod_whenAMatchingEventIsPosted() throws InterruptedException {

        System.out.println("Start Kalium-Kafka Basic End-2-End Test");
        KaliumQueueAdapter queueAdapter1 = new KaliumKafkaQueueAdapter(KAFKA_ENDPOINT);

        MyReaction myReaction = Mockito.spy(new MyReaction());
        MyReaction2 myReaction2 = Mockito.spy(new MyReaction2());
        Kalium kalium1 = Kalium.Builder()
                .setQueueAdapter(queueAdapter1)
                .build();
        kalium1.addReaction(myReaction);
        kalium1.addReaction(myReaction2);
        kalium1.start();

        KaliumQueueAdapter queueAdapter2 = new KaliumKafkaQueueAdapter(KAFKA_ENDPOINT);
        Kalium kalium2 = Kalium.Builder()
                .setQueueAdapter(queueAdapter2)
                .build();
        kalium2.start();

        Payment payment = new Payment(UUID.randomUUID().toString());

        kalium2.post(payment);


        Thread.sleep(6000);

        synchronized (myReaction) {
            ArgumentCaptor<Payment> argumentCaptor = ArgumentCaptor.forClass(Payment.class);
            Mockito.verify(myReaction).doSomething(argumentCaptor.capture());
            Payment capturedArgument = argumentCaptor.<Payment>getValue();
            Assert.assertEquals(capturedArgument.getId(), payment.getId());
        }

        synchronized (myReaction2) {
            ArgumentCaptor<Payment> argumentCaptor = ArgumentCaptor.forClass(Payment.class);
            Mockito.verify(myReaction2).doSomething(argumentCaptor.capture());
            Payment capturedArgument = argumentCaptor.<Payment>getValue();
            Assert.assertEquals(capturedArgument.getId(), payment.getId());
        }


    }


}
