package io.alkal.kalium.kafka.tests;/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import io.alkal.kalium.kafka.Constants;
import io.alkal.kalium.kafka.ProtoUtils;
import io.alkal.kalium.kafka.ProtobufDeSerializer;
import io.alkal.kalium.kafka.tests.pb.Payment;
import org.apache.kafka.common.errors.SerializationException;
import org.junit.Test;

import java.lang.reflect.Method;
import java.util.HashMap;
import java.util.Map;

import static org.junit.Assert.*;


public class ProtoUtilsTest {


    @Test(expected = NoSuchMethodException.class)
    public void testGetParseFromMethod_shouldThrowException_whenNoProtoClassIsUsed() throws NoSuchMethodException {
        ProtoUtils.getParseFromMethod(String.class);
    }

    @Test
    public void testGetParseFromMethod_shouldReturnParseFromMethod_whenProtoClassIsUsed() throws NoSuchMethodException {
        Method m = ProtoUtils.getParseFromMethod(Payment.PaymentPB.class);
        assertEquals("parseFrom", m.getName());
    }


    @Test
    public void testIsProtoClass_shouldReturnTheCorrectAnswer() {
        assertTrue(ProtoUtils.isProtoClass(Payment.PaymentPB.class));
        assertFalse(ProtoUtils.isProtoClass(io.alkal.kalium.kafka.tests.Payment.class));
    }


}
