package io.alkal.kalium.kafka.tests;/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import io.alkal.kalium.kafka.ProtobufSerializer;
import io.alkal.kalium.kafka.tests.models.pb.Payment;
import org.junit.Test;

import static org.junit.Assert.*;


public class ProtobufSerializerTest {

    public static final String payment_id = "cdb0dfb9-396d-4269-bfa4-8408211b5e3d";
    public static final Payment.PaymentPB payment = Payment.PaymentPB.newBuilder().setId(payment_id).setProcessed(false).build();
    public static final byte[] validSerializedPayment = payment.toByteArray();

    private ProtobufSerializer target = new ProtobufSerializer();


    @Test
    public void testSerialize_whenObjectNull_shouldReturnNullObject() {
        Object o = target.serialize("Payment", null);
        assertNull(o);
    }


    @Test
    public void testSerializePayment_shouldReturnCorrectBytes() {
        byte[] bytes = target.serialize("Payment", payment);
        assertTrue("byte[] is empty", bytes != null && bytes.length > 0);
        assertArrayEquals(validSerializedPayment, target.serialize("Payment", payment));
    }
}
